### ISSUE TITLE
Multiple inheritance on 'social role'

### ISSUE THREAD

**Issue by dillerm** [Superraptor/GSSO#1]
Currently, 'social role' is classified in GSSO as a subclass of both 'role' and 'social group process'. Because, in BFO, roles are entities that are realized by processes, this may lead to contradictions down the road. Simply removing the subClassOf relation between 'social role' and 'social group processes' would resolve this.

**Comment by Superraptor** [comment]
The original decision to provide "social role" under both classes was to indicate that the social role in and of itsefl is a process (in a sociological sense). However, I don't see any issues with removing it as it stands, I'll change and update ASAP. Thanks for your patience!
