### ISSUE TITLE
New Term Request : 'Boot'

### ISSUE THREAD

**Issue by Anoosha-Sehar** [Superraptor/GSSO#10]
Dear GSSO curators,

I would like to submit a request to add a new term 'boot'.

Term Label: boot
Definition: Footwear that covers the foot, the ankle, and sometimes the leg below the knee.
Parent class: footwear ([http://purl.obolibrary.org/obo/GSSO_004998](http://purl.obolibrary.org/obo/GSSO_004998))
Database cross reference : [https://www.oxfordlearnersdictionaries.com/definition/english/boot_1#:~:text=a%20strong%20shoe%20that%20covers,(British%20English)%20walking%20boots](url)
Alternate name: boots

Thank you, 

Anoosha

**Comment by Superraptor** [comment]
Thank you so much for the recommendation! I have added it in 2.0.9 as GSSO:012935. Note that it may take some time for the PURLs to update.

**Comment by Anoosha-Sehar** [comment]
That's perfect!! Thank you so much, Clair.

**Comment by Superraptor** [comment]
Of course! Let me know if you need anything else:)

**Comment by nikelborm** [comment]
I mean why? How is this related to gender or sexual orientations?
// Sincere question
