### ISSUE TITLE
Overlap between gender and gender identity classes in GSSO and OMRSE

### ISSUE THREAD

**Issue by dillerm** [Superraptor/GSSO#2]
We recently did some work in the Ontology for Medically Related Social Entities on representing gender identities that we thought we'd make you aware of. Our approach to representing them is informed by a past writing on how to represent 'phenotypic sex' and 'gender' (http://ceur-ws.org/Vol-833/paper20.pdf), as well as our general understanding of these entities. We therefore wanted to reach out to see if you'd be interested in either reusing our classes or discussing how to consolidate our representations of these entities. 

A comparison of our definition of 'gender role' and yours:

> gender role (OMRSE:00000007) = A human social role borne by a human being being realized in behaviour which is considered socially appropriate for individuals of a specific sex in the context of a specific culture.

> gender role (GSSO:000087) = A gender role is a social role encompassing a range of behaviors and attitudes that are generally considered culturally and/or socially acceptable, appropriate, or desirable for people based on their actual or perceived gender, sex and/or sexuality.

The differences between our definitions, I think, are rather minimal and should be easy to reach a consensus on.

A comparison of our representation of gender identity to yours, which looks to be imported from MeSH:

> gender identity information content entity (OMRSE:00000209) = A social identity information content entity that is about whether some person identifies as some gender.

> gender identity (MESH:D005783) = A person's concept of self as being male and masculine or female and feminine, or ambivalent, based in part on physical characteristics, parental responses, and psychological and social pressures. It is the internal experience of gender role.

I should note here that the work we did on gender identity is very recent and probably wasn't available when you first started working on GSSO. The key differences between the two classes is that we define 'gender identity information content entity' as an information content entity (ICE), whereas MeSH defines 'gender identity' it as a personal attribute. Our reasoning for defining 'gender identity' as such is largely because we understand gender identity to be something that can be fluid throughout an individual's life (for more information on our reasoning here, see our [definition and comment for 'social identity information content entity'](http://www.ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/OMRSE_00000204)). Another reason not mentioned in our classes is that we believe it's important to distinguish between people who truly do identify as a particular gender identity and those who do not (e.g., simply saying that you identify as a particular gender is not enough, you have sincerely mean it).

**Comment by Superraptor** [comment]
I think ultimately despite the small differences in definitions that I can shift "gender role" to an OMRSE IRI if that's preferable on your end. Therefore I've shifted "gender role", "female gender role", and "male gender role" to their respective OMRSE IRIs, and kept the old IRIs in comment form if remapping is necessary.

For "gender identity" and related entities there have been many changes recently as a result of working on the Gender Harmony Project with HL7. The difference between the GSSO and OMRSE entities is that OMRSE represents the datum (the recorded gender identity as information), while GSSO represents the broader concept of oneself. For instance, a pre-transition trans woman can (and probably should) lie about her gender identity as female for safety reasons in some situations, but her gender identity is still female. In this case, it is possible for a gender identity information content entity and a gender identity to be different. I think a "related synonym" is best for now, within the GSSO at least. 

I'll update today, but keep this open in case you have any further comments! Thank you for your patience.

(Edit: Note that the files on GitHub will always be the most up-to-date; since we are running a survey on the main site right now, we aren't updating those files as often)

**Comment by dillerm** [comment]
So I actually think that it might be better to add our gender role classes to GSSO (i.e., give them GSSO IRIs) since the ontology's domain specifically encompasses gender identity (and then we would just import the GSSO class into OMRSE). I'll have to discuss this further with the rest of the OMRSE team, though. 

I see your point about the need to distinguish between gender identity and information about gender identities, although I wonder if the [Mental Functioning Ontology's 'cognitive representation'](http://www.ontobee.org/ontology/MF?iri=http://purl.obolibrary.org/obo/MF_0000031) class would be a better parent for 'gender identity' than MeSH's 'attribute' class. Is GSSO part of the HL7 Gender Harmony Project, and if so, are you constrained to using MeSH's hierarchy here (if I might ask)?

**Comment by Superraptor** [comment]
It's currently under personal attribute and self-identity, which I believe covers the representation portion in my opinion. But I can be amendable to any of various conversations moving forward. Note that the GSSO is in use by archivists and librarians in addition to medical researchers, EHR-related standardizations, and NLP platforms, so it's always attempting a delicate balancing act between these constituent groups. We are not officially constrained by any means, just held to the experiences of various user groups. The GSSO is not currently officially connected to the Gender Harmony Project, but will likely have a full mapping and has contributed material to the HL7 Gender Harmony Project as it currently stands (and may become ballot material next month).

EDIT: I'll close this issue for the time being until there is further clarification / suggestions on potential mapping.

**Comment by dillerm** [comment]
Oh, wow, I just realized I completely did not type the right thing! I meant to say that it might be better for OMRSE to import GSSO's 'gender role' classes (I have no idea how that came out completely backwards). In any case, I spoke to our team and it seems like they would prefer to keep the OMRSE IRI for 'gender role' since it's been in production and use for a while now.

**Comment by Superraptor** [comment]
@dillerm oh! no worries! please let me know if there's any way I can help with anything or contribute further!
