### ISSUE TITLE
Maximising interoperability: using OBO NCBI taxon purls

### ISSUE THREAD

**Issue by matentzn** [Superraptor/GSSO#6]
I dont know the history behind this, but there seem to be two different ID schemes for NCBI taxon:

http://purl.bioontology.org/ontology/NCBITAXON/135663

and 

http://purl.obolibrary.org/obo/NCBITaxon_135663

To maximise the interoperability with other OBO ontologies, it would be good if you could use the latter. You could just use string+replace in your ontology, and it would work I think. The reason is this:

Search engines such as OLS are heavily used by curators; now they are swamped with two alternative NCBITAXON ids.. I think it would be good to normalise..

**Comment by Superraptor** [comment]
Thanks for noting! Originally I was using the IRIs from the NCBO BioPortal version. I've changed this as of the 2.0.5 beta and pushed it to GitHub.

**Comment by matentzn** [comment]
Awesome!
